Task 8
cocicka21/JavaCourseRepository pull request #18
Opened 2023-03-01 19:25 UTC by cocicka21

2023-03-28 13:24 UTC, Willynick requested changes

2023-03-28 13:24 UTC, Willynick commented on it/academy/course/hw8/task1/Home8Task_1.java
> +                System.out.println("Cooking with " + str);
Здесь можно прописать реальный рецепт, но ладно)

2023-03-28 13:24 UTC, Willynick commented on it/academy/course/hw8/task3/Home8Task_3.java
> +        Cloth cloth2 = null;
А почему nullы есть?

2023-03-28 13:24 UTC, Willynick commented on it/academy/course/hw8/task3/Home8Task_3.java
> +        boolean boughtShoes = shop.buyShoes(shoes2);
Получается у нас только одни такие туфли могут быть в магазине? Но у нас же может их быть большое количество. Поэтому давай добавим логику, где может быть много копий товаров

2023-04-02 11:07 UTC, merged

2023-04-05 09:39 UTC, cocicka21 commented on it/academy/course/hw8/task3/Home8Task_3.java
> +        Cloth cloth2 = null;
Это для примера, условно, если на сайте можно выбрать товар, а на самом деле его нету